<a href="https://colab.research.google.com/github/Datasci266-Final-Project/Job-Listings/blob/main/Analysis%20Notebooks/Test_Result_Analysis_Frank.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

%cd /content/drive/My Drive/DS 266 Project

Mounted at /content/drive
/content/drive/My Drive/DS 266 Project

In [ ]:
!ls

'Data Sci 266 Project Proposal Ideas_18Feb24.docx'   my_word2vec_model.model.syn1neg.npy
 Frank_EDA_Playground.ipynb			     my_word2vec_model.model.wv.vectors.npy
'labeled_job_data (1).csv'			     Pascual_Draft_EDA_Model.ipynb
 labeled_job_data.csv				    'Project Proposal.docx'
 lu_data_job_titles.csv				     sample_data.csv
'MM_Draft Project Notebook.ipynb'		     sample_data_job_titles.csv
 model.png					     test_data_predictions_final.csv
 Multiclass_text_classification_copy1.ipynb	     test_data_with_predictions.csv
 my_word2vec_model.model			     Test_Result_Analysis_Template.ipynb

In [ ]:
test_data = pd.read_csv('test_data_predictions_final.csv')

In [ ]:
len(test_data)

14063

In [ ]:
test_data.head()

,index,title,text,level,salary,salary_bucket,level_labels,salary_labels,level_predictions_bert_base,level_predictions_xlm_roberta,level_predictions_jobbert,salary_predictions_bert_base,salary_predictions_xlm_roberta,salary_predictions_jobbert,level_predictions_dan,salary_predictions_dan,language,language_full_name,salary_labels_baseline
0,17953,Real Estate Fund Accounting Senior Client Mana...,Credit Suisse is a leading global wealth manag...,senior,NaN,NaN,4,-1,1,5,4,1,2,1,3,3,en,English,-1
1,97031,Investment Analyst,<p><strong><u>INVESTMENT ANALYST in Luxembourg...,junior,NaN,NaN,2,-1,3,2,3,2,1,1,2,3,en,English,-1
2,64933,Accounts payable accountant Fr-En (M/F),Job Description LE POSTE : For one of our clie...,NaN,55000.0,50-100k,-1,1,2,1,2,1,0,1,1,2,en,English,1
3,79240,Concepteur d'offres de formation - Division du...,Missions Le concepteur dâ€™offre sera en charge ...,entry,NaN,NaN,1,-1,1,4,1,0,1,1,5,6,fr,French,-1
4,89706,SC Analyst,"Description At Amazon Logistics (AMZL), we str...",junior,NaN,NaN,2,-1,4,4,3,1,1,2,2,6,en,English,-1

In [ ]:
test_data_1 = test_data.iloc[0:5000,:]
test_data_2 = test_data.iloc[5000:10000,:]
test_data_3 = test_data.iloc[10000:,:]

In [ ]:
test_data_3.head()

,index,title,text,level,salary,salary_bucket,level_labels,salary_labels,level_predictions_bert_base,level_predictions_xlm_roberta,level_predictions_jobbert,salary_predictions_bert_base,salary_predictions_xlm_roberta,salary_predictions_jobbert,level_predictions_dan,salary_predictions_dan,language,language_full_name,salary_labels_baseline
10000,79894,"Senior Finance Analyst, Inbound Supply Chain F...",Job Summary DESCRIPTION â€œHave you ever ordered...,senior,NaN,NaN,4,-1,3,3,3,1,1,2,3,5,en,English,-1
10001,90948,Java Developer,About The Job Toptal developers work with spee...,mid,NaN,NaN,3,-1,3,3,3,2,3,2,3,3,en,English,-1
10002,61239,LINUX SUPPORT ENGINEER | Start-up - Luxemburg ...,LINUX SUPPORT ENGINEER (FR/EN) - Missions Eval...,entry,NaN,NaN,1,-1,1,1,1,1,0,1,1,6,en,English,-1
10003,73643,Group Financial Reporting Specialist,Ferrero is a family-owned company with a truly...,senior,NaN,NaN,4,-1,3,3,3,2,2,2,3,3,en,English,-1
10004,26585,Doctoral Researcher on DIgitaLisation Law And ...,The University of Luxembourg aspires to be one...,senior,NaN,NaN,4,-1,4,4,4,1,1,2,0,3,en,English,-1

In [ ]:
test_data_3.count()

index                             4063
title                             4063
text                              4063
level                             3554
salary                             666
salary_bucket                      666
level_labels                      4063
salary_labels                     4063
level_predictions_bert_base       4063
level_predictions_xlm_roberta     4063
level_predictions_jobbert         4063
salary_predictions_bert_base      4063
salary_predictions_xlm_roberta    4063
salary_predictions_jobbert        4063
level_predictions_dan             4063
salary_predictions_dan            4063
language                          4062
language_full_name                4062
salary_labels_baseline            4063
dtype: int64

In [ ]:
len_test_data_3 = len(test_data_3)
len_test_data_3

4063

In [ ]:
df_BERT_salary_match = np.where(test_data_3['salary_labels'] == test_data_3['salary_predictions_bert_base'])
df_Jobbert_salary_match = np.where(test_data_3['salary_labels'] == test_data_3['salary_predictions_jobbert'])
df_Roberta_salary_match = np.where(test_data_3['salary_labels'] == test_data_3['salary_predictions_xlm_roberta'])
df_DAN_salary_match = np.where(test_data_3['salary_labels'] == test_data_3['salary_predictions_dan'])

df_BERT_level_match = np.where(test_data_3['level_labels'] == test_data_3['level_predictions_bert_base'])
df_Jobbert_level_match = np.where(test_data_3['level_labels'] == test_data_3['level_predictions_jobbert'])
df_Roberta_level_match = np.where(test_data_3['level_labels'] == test_data_3['level_predictions_xlm_roberta'])
df_DAN_level_match = np.where(test_data_3['level_labels'] == test_data_3['level_predictions_dan'])

In [ ]:
print("salary test BERT - base: ", len(df_BERT_salary_match[0]))
print("salary test Jobbert: ", len(df_Jobbert_salary_match[0]))
print("salary test Roberta: ", len(df_Roberta_salary_match[0]))
print("salary test DAN: ", len(df_DAN_salary_match[0]))
print()
print("level test BERT - base: ", len(df_BERT_level_match[0]))
print("level test Jobbert: ", len(df_Jobbert_level_match[0]))
print("level test Roberta: ", len(df_Roberta_level_match[0]))
print("level test DAN: ", len(df_DAN_level_match[0]))
print()

print("salary test BERT - base: ", len(df_BERT_salary_match[0])/len_test_data_3)
print("salary test Jobbert: ", len(df_Jobbert_salary_match[0])/len_test_data_3)
print("salary test Roberta: ", len(df_Roberta_salary_match[0])/len_test_data_3)
print("salary test DAN: ", len(df_DAN_salary_match[0])/len_test_data_3)
print()
print("level test BERT - base: ", len(df_BERT_level_match[0])/len_test_data_3)
print("level test Jobbert: ", len(df_Jobbert_level_match[0])/len_test_data_3)
print("level test Roberta: ", len(df_Roberta_level_match[0])/len_test_data_3)
print("level test DAN: ", len(df_DAN_level_match[0])/len_test_data_3)

salary test BERT - base:  463
salary test Jobbert:  491
salary test Roberta:  472
salary test DAN:  163

level test BERT - base:  2319
level test Jobbert:  2411
level test Roberta:  2377
level test DAN:  1082

salary test BERT - base:  0.11395520551316761
salary test Jobbert:  0.12084666502584297
salary test Roberta:  0.1161703174993847
salary test DAN:  0.040118139305931576

level test BERT - base:  0.5707605217819345
level test Jobbert:  0.5934038887521536
level test Roberta:  0.5850356879153334
level test DAN:  0.26630568545409794

In [ ]:
df_DAN_salary_match[0]

array([   9,   26,   55,   89,   92,   97,  107,  113,  135,  172,  175,
        179,  198,  213,  237,  247,  276,  299,  341,  356,  388,  391,
        447,  452,  483,  493,  497,  527,  556,  573,  643,  658,  679,
        686,  695,  711,  724,  734,  800,  861,  883,  892,  919, 1005,
       1023, 1056, 1069, 1119, 1223, 1244, 1274, 1290, 1292, 1303, 1314,
       1351, 1369, 1418, 1460, 1469, 1480, 1492, 1526, 1539, 1557, 1578,
       1635, 1645, 1669, 1679, 1695, 1700, 1705, 1765, 1771, 1791, 1814,
       1819, 1921, 1924, 1926, 1942, 1991, 2081, 2153, 2164, 2196, 2226,
       2248, 2256, 2299, 2333, 2335, 2376, 2447, 2449, 2460, 2480, 2497,
       2506, 2563, 2574, 2615, 2626, 2628, 2635, 2659, 2733, 2789, 2850,
       2855, 2870, 2959, 2977, 3022, 3044, 3051, 3068, 3074, 3087, 3121,
       3122, 3132, 3160, 3166, 3185, 3190, 3205, 3222, 3228, 3232, 3237,
       3292, 3303, 3346, 3388, 3460, 3512, 3532, 3552, 3558, 3570, 3582,
       3630, 3652, 3660, 3664, 3675, 3678, 3693, 3704, 3708, 3736, 3787,
       3797, 3799, 3813, 3817, 3831, 3861, 3944, 3973, 4059])

level test BERT - base:  4063
level test Jobbert:  4063
level test Roberta:  4063
level test DAN:  4063

**Frank's Note - test_data_3**

Performance of level predictions is better than that of salary across all models. For all 4 models and both predictions, performance is Jobbert > Roberta > BERT Base > DAN